// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxLlrF4GEjj7fZVxV73QP0JRIIZlNl9lk',
    appId: '1:436200698445:web:3c76b04fb1380a3f3da204',
    messagingSenderId: '436200698445',
    projectId: 'hujambo-app',
    authDomain: 'hujambo-app.firebaseapp.com',
    storageBucket: 'hujambo-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwiJc85_Qa3Jo3kdeaxX8FGVQdQofknPk',
    appId: '1:436200698445:android:f7ce7f83d6250ac93da204',
    messagingSenderId: '436200698445',
    projectId: 'hujambo-app',
    storageBucket: 'hujambo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCemXuiseairJUhNuKZb0EBbWfhqZLKvxQ',
    appId: '1:436200698445:ios:1b0ccd5615d453773da204',
    messagingSenderId: '436200698445',
    projectId: 'hujambo-app',
    storageBucket: 'hujambo-app.appspot.com',
    iosClientId: '436200698445-iokcr6uuumfimrrp7g4iukcorvejthe2.apps.googleusercontent.com',
    iosBundleId: 'com.example.hujambo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCemXuiseairJUhNuKZb0EBbWfhqZLKvxQ',
    appId: '1:436200698445:ios:1b0ccd5615d453773da204',
    messagingSenderId: '436200698445',
    projectId: 'hujambo-app',
    storageBucket: 'hujambo-app.appspot.com',
    iosClientId: '436200698445-iokcr6uuumfimrrp7g4iukcorvejthe2.apps.googleusercontent.com',
    iosBundleId: 'com.example.hujambo',
  );
}
